markdown: kramdown
highlighter: null
permalink: pretty
url: https://fontforge.org/
plugins:
  - jekyll-redirect-from
include:
  - _images
  - _static
socialTitle: FontForge
socialDescription: FontForge is a free and open-source outline font editor.
socialImage: /assets/img/social-banner.png
socialAuthor: '@fontforge'
